"""Schema for console-editable Home Suite configuration values.

The schema is intentionally narrower than app_config.py. It covers values that
can be represented and validated without an arbitrary-code editor. Purpose-built
console editors handle structured room topology, GPIO button mappings, and
device-local microphone profiles.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


DEPLOYMENT_CONFIG_FILE = "deployment_config.py"
LOCAL_PREFS_FILE = "local_prefs.py"
PRIVATE_CONFIG_FILE = "private_config.py"


@dataclass(frozen=True)
class ConfigField:
    key: str
    section: str
    section_label: str
    target_file: str
    value_type: str
    label: str
    description: str
    surface: str = "settings"
    placeholder: str = ""
    help_text: str = ""
    docs_path: str = ""
    required: bool = False
    secret: bool = False
    allow_empty: bool = True
    choices: tuple[tuple[str, str], ...] = ()
    dynamic_choices: Optional[str] = None
    minimum: Optional[float] = None
    maximum: Optional[float] = None
    pattern: Optional[str] = None
    restart_services: tuple[str, ...] = ("homesuite.service",)


def _local(
    key: str,
    section: str,
    section_label: str,
    value_type: str,
    label: str,
    description: str,
    **kwargs,
) -> ConfigField:
    return ConfigField(
        key=key,
        section=section,
        section_label=section_label,
        target_file=LOCAL_PREFS_FILE,
        value_type=value_type,
        label=label,
        description=description,
        **kwargs,
    )


def _deployment(
    key: str,
    section: str,
    section_label: str,
    value_type: str,
    label: str,
    description: str,
    **kwargs,
) -> ConfigField:
    return ConfigField(
        key=key,
        section=section,
        section_label=section_label,
        target_file=DEPLOYMENT_CONFIG_FILE,
        value_type=value_type,
        label=label,
        description=description,
        **kwargs,
    )


def _private(
    key: str,
    section: str,
    section_label: str,
    value_type: str,
    label: str,
    description: str,
    **kwargs,
) -> ConfigField:
    kwargs.setdefault("surface", "integrations")
    return ConfigField(
        key=key,
        section=section,
        section_label=section_label,
        target_file=PRIVATE_CONFIG_FILE,
        value_type=value_type,
        label=label,
        description=description,
        **kwargs,
    )


EDITABLE_FIELDS = (
    _local(
        "DEFAULT_ROOM",
        "node",
        "Node and role",
        "choice",
        "Default room",
        "Room used when a request does not provide a more specific source room.",
        help_text="The choices come from the shared Rooms registry. Add or duplicate rooms in the Rooms tab, then select the room this node should use by default.",
        docs_path="docs/ROOM_CONFIGURATION.md",
        required=True,
        allow_empty=False,
        dynamic_choices="rooms",
    ),
    _local(
        "PTT_ENABLED",
        "ptt",
        "Push-to-talk (PTT)",
        "boolean",
        "Enable PTT",
        "Uses a maintained GPIO input to open and close microphone listening sessions.",
        help_text="Enable for a held push-to-talk button, telephone hook, foot switch, or another control that remains in one state while Home Suite should listen.",
        docs_path="docs/PTT.md",
        surface="controls",
    ),
    _local(
        "PTT_GPIO_PIN",
        "ptt",
        "Push-to-talk (PTT)",
        "integer",
        "BCM GPIO pin",
        "GPIO input connected to the PTT control, using Raspberry Pi BCM numbering.",
        placeholder="11",
        help_text="BCM numbering is not the physical header-pin number. The default is BCM 11; choose a pin that is not assigned to another configured input.",
        docs_path="docs/PTT.md",
        required=True,
        allow_empty=False,
        minimum=0,
        maximum=27,
        surface="controls",
    ),
    _local(
        "PTT_LISTEN_LEVEL",
        "ptt",
        "Push-to-talk (PTT)",
        "choice",
        "Listen when input is",
        "GPIO level that means the PTT listening session is active.",
        help_text="Choose Low for a control that connects the pin to ground while listening. Choose High only for inverse wiring. Switch mechanics vary, so this is more reliable than assuming pressed or released.",
        docs_path="docs/PTT.md",
        required=True,
        allow_empty=False,
        choices=(("low", "Low (connected to ground)"), ("high", "High (inverse wiring)")),
        surface="controls",
    ),
    _local(
        "PTT_END_BEHAVIOR",
        "ptt",
        "Push-to-talk (PTT)",
        "choice",
        "When the listening state ends",
        "Chooses whether speech already captured is submitted or discarded.",
        help_text="Use Submit for a conventional hold-to-talk button where release finishes the utterance. Use Cancel for a telephone hook where hanging up should discard partial speech and stop the response.",
        docs_path="docs/PTT.md",
        required=True,
        allow_empty=False,
        choices=(("submit", "Submit captured speech"), ("cancel", "Cancel captured speech")),
        surface="controls",
    ),
    _local(
        "START_CHIME_DELAY_SECONDS",
        "ptt",
        "Push-to-talk (PTT)",
        "number",
        "Start cue delay",
        "Seconds to wait after PTT activates before playing its first listening cue.",
        placeholder="0.0",
        help_text="Use 0 for an immediate cue. A telephone handset may need a small delay so the receiver reaches the user's ear first.",
        docs_path="docs/PTT.md",
        minimum=0.0,
        maximum=5.0,
        surface="controls",
    ),
    _local(
        "WAKEWORD_SUPPRESS_WHILE_PTT",
        "ptt",
        "Push-to-talk (PTT)",
        "boolean",
        "Pause wake-word detection during PTT",
        "Prevents the wake-word path from triggering while a PTT session is active.",
        help_text="Keep enabled when one device supports both interaction modes so PTT audio is not interpreted as a second wake-word interaction.",
        docs_path="docs/PTT.md",
        surface="controls",
    ),
    _local(
        "WAKEWORD_ENABLED",
        "wakeword_models",
        "Wake-word models",
        "boolean",
        "Wake-word listening",
        "Runs continuous wake-word detection on this node.",
        help_text="Enable only after the microphone and wake-word model are configured and calibrated.",
        docs_path="docs/WAKEWORD.md",
        surface="managed",
    ),
    _local(
        "COMMAND_PROCESSING_MODE",
        "satellite",
        "Command processing",
        "choice",
        "Process voice commands on",
        "Chooses whether this node executes transcripts itself or sends them to another Home Suite node.",
        help_text="This device is the normal all-in-one mode. Another Home Suite instance keeps microphone capture, wake-word/PTT, transcription, cues, and spoken responses here while the other instance handles routing, continuity, AI, and actions.",
        docs_path="docs/API.md",
        required=True,
        allow_empty=False,
        choices=(("local", "This device"), ("satellite", "Another Home Suite instance")),
    ),
    _local(
        "SATELLITE_BRAIN_URL",
        "satellite",
        "Command processing",
        "url",
        "Other Home Suite URL",
        "Authenticated Home Suite companion API that receives this node's transcripts.",
        placeholder="http://another-homesuite.local:8765",
        help_text="Enter the other instance's server URL or its full /command URL. It must be reachable from this device and use the same API key unless a separate key is entered below.",
        docs_path="docs/API.md",
    ),
    _local(
        "WAKEWORD_ARBITRATION_ENABLED",
        "wakeword_arbitration",
        "Multi-device coordination",
        "boolean",
        "Coordinate wake-word devices",
        "Lets one Home Suite brain choose which linked wake-word device handles a shared utterance.",
        help_text="A single connected wake-word device is granted immediately. When several devices hear the same wake word, only the best candidate acknowledges and processes it. PTT is unaffected.",
        docs_path="docs/API.md",
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_ARBITRATION_ELECTION_WINDOW_MS",
        "wakeword_arbitration",
        "Multi-device coordination",
        "number",
        "Multi-device decision window",
        "Milliseconds the brain waits for competing wake hits when several eligible devices are online.",
        placeholder="180",
        help_text="This delay is skipped entirely for a one-device cluster. Keep it short; all candidates continue buffering speech while the brain decides.",
        docs_path="docs/API.md",
        minimum=0,
        maximum=1000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_ARBITRATION_COHORT_WINDOW_MS",
        "wakeword_arbitration",
        "Multi-device coordination",
        "number",
        "Shared-wake matching window",
        "Maximum timestamp separation for wake hits to be treated as one acoustic event.",
        placeholder="700",
        help_text="This groups detector decisions that arrive at slightly different times without using HTTP arrival order as the source of truth.",
        docs_path="docs/API.md",
        minimum=100,
        maximum=3000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_ARBITRATION_DECISION_TIMEOUT_MS",
        "wakeword_arbitration",
        "Multi-device coordination",
        "number",
        "Decision timeout",
        "Maximum time a satellite waits for the brain's grant or suppression decision.",
        placeholder="750",
        help_text="A device that has previously seen a multi-device cluster fails closed if coordination is unavailable, preventing duplicate commands.",
        docs_path="docs/API.md",
        minimum=100,
        maximum=3000,
        surface="wakeword",
    ),
    _deployment(
        "ASSISTANT_PROFILE",
        "assistant_context",
        "Assistant context",
        "json_object",
        "About this household",
        "Optional shared context used to make conversational answers more relevant.",
        placeholder='{"preferred_name": "", "locale": "", "units": "", "notes": []}',
        help_text="Use preferred_name, locale, units, and notes. Do not include secrets, access codes, precise addresses, or facts that should not be sent to the configured AI provider.",
        docs_path="docs/CONFIGURATION.md",
    ),
    _deployment(
        "CALENDARS",
        "calendars",
        "Calendars",
        "json_object",
        "Available calendars",
        "Maps friendly calendar names to Home Assistant calendar entities and access policy.",
        placeholder='{"personal": {"entity_id": "calendar.personal", "label": "Personal", "aliases": ["my calendar"], "writable": true, "include_in_agenda": true}}',
        help_text="Each entry needs a calendar.* entity_id. Writable and include_in_agenda are optional booleans; aliases is an optional list of spoken names.",
        docs_path="docs/CONFIGURATION.md",
    ),
    _deployment(
        "DEFAULT_CALENDAR",
        "calendars",
        "Calendars",
        "choice",
        "Default calendar",
        "Calendar used for event creation when a command does not name one.",
        help_text="Choices come from Available calendars. Automatic leaves event creation without an implicit calendar selection.",
        docs_path="docs/CONFIGURATION.md",
        dynamic_choices="calendars_optional",
    ),
    _deployment(
        "CALENDAR_READS_ENABLED",
        "calendars",
        "Calendars",
        "boolean",
        "Allow calendar queries",
        "Allows Home Suite to answer read-only agenda and event questions.",
        help_text="Disable only when this deployment should ignore configured Home Assistant calendars entirely.",
        docs_path="docs/CONFIGURATION.md",
    ),
    _deployment(
        "CALENDAR_WRITES_ENABLED",
        "calendars",
        "Calendars",
        "boolean",
        "Allow event creation",
        "Allows confirmed commands to create events on calendars marked writable.",
        help_text="Keep disabled until at least one Available calendars entry is deliberately marked writable.",
        docs_path="docs/CONFIGURATION.md",
    ),
    _deployment(
        "CALENDAR_CONFIRM_WRITES",
        "calendars",
        "Calendars",
        "boolean",
        "Confirm new events",
        "Requires spoken or typed confirmation before a calendar event is created.",
        help_text="Keeping confirmation enabled is recommended for every voice-controlled calendar.",
        docs_path="docs/CONFIGURATION.md",
    ),
    _deployment(
        "CALENDAR_DEFAULT_EVENT_DURATION_MINUTES",
        "calendars",
        "Calendars",
        "integer",
        "Default event duration",
        "Minutes used when an event command does not include an end time or duration.",
        placeholder="60",
        help_text="Choose a whole number from 1 minute through 24 hours. This is used only when the command supplies no duration.",
        docs_path="docs/CONFIGURATION.md",
        required=True,
        allow_empty=False,
        minimum=1,
        maximum=1440,
    ),
    _local(
        "WAKEWORD_ENGINE",
        "wakeword",
        "Detection",
        "choice",
        "Detection engine",
        "Wake-word engine used for continuous local detection.",
        help_text="OpenWakeWord supports local ONNX models. Porcupine requires a Picovoice access key.",
        docs_path="docs/WAKEWORD.md",
        required=True,
        allow_empty=False,
        choices=(("openwakeword", "OpenWakeWord"), ("porcupine", "Porcupine")),
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_MODEL",
        "wakeword_models",
        "Wake-word models",
        "string",
        "Model label",
        "Model name used to select a wake word from the engine's loaded models.",
        placeholder="hal_v2",
        help_text="Use the label reported in WAKEWORD_ENGINE_OPENWAKEWORD_MODELS. It may be blank when model paths provide multiple labels.",
        docs_path="docs/WAKEWORD.md",
        surface="managed",
    ),
    _local(
        "WAKEWORD_MODEL_PATHS",
        "wakeword_models",
        "Wake-word models",
        "list_string",
        "Custom model paths",
        "One local ONNX model path per line for custom OpenWakeWord models.",
        placeholder="/home/jayore/wake_models/hal.onnx",
        help_text="Leave empty to use models bundled with the selected engine. Paths must exist on this node.",
        docs_path="docs/WAKEWORD.md",
        surface="managed",
    ),
    _local(
        "WAKEWORD_THRESHOLD",
        "wakeword",
        "Detection",
        "number",
        "Detection threshold",
        "Minimum model score required to trigger the wake word.",
        placeholder="0.50",
        help_text="Higher values reduce false triggers but can increase missed wake words. Tune from captured samples rather than guessing.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=1.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_VAD_THRESHOLD",
        "wakeword",
        "Detection",
        "number",
        "Voice activity threshold",
        "Minimum speech probability required alongside the wake-word score.",
        placeholder="0.50",
        help_text="Set to 0 to disable the VAD gate. Higher values reject more non-speech audio but may reject quiet speech.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=1.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_DEBOUNCE_SEC",
        "wakeword_detection_advanced",
        "Advanced detection",
        "number",
        "Repeat-trigger floor",
        "Minimum seconds between accepted wake-word detections.",
        placeholder="0.30",
        help_text="Hysteresis is the primary duplicate-hit protection. Keep this short so it blocks duplicate frames without creating a noticeable refractory period.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=10.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_ACTIVATION_WINDOW_FRAMES",
        "wakeword_detection_advanced",
        "Advanced detection",
        "integer",
        "Activation window",
        "Recent model frames considered when deciding whether a score is a real trigger.",
        placeholder="3",
        help_text="A larger window smooths uneven scores but can add detection latency. Most installations should keep the default.",
        docs_path="docs/WAKEWORD.md",
        minimum=1,
        maximum=30,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_DEACTIVATION_THRESHOLD",
        "wakeword_detection_advanced",
        "Advanced detection",
        "number",
        "Rearm score",
        "Score every active model must fall below before detection can rearm.",
        placeholder="0.20",
        help_text="Keep this below the normal Detection threshold so one spoken wake word cannot produce repeated hits while its score decays.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=1.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_DEACTIVATION_FRAMES",
        "wakeword_detection_advanced",
        "Advanced detection",
        "integer",
        "Rearm frames",
        "Consecutive low-score frames required before detection rearms.",
        placeholder="3",
        help_text="Raise this only when a model produces repeated hits from the tail of one utterance.",
        docs_path="docs/WAKEWORD.md",
        minimum=1,
        maximum=60,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_NEAR_MISS_MIN_SCORE",
        "wakeword_detection_advanced",
        "Advanced detection",
        "number",
        "Near-miss logging score",
        "Lowest model score recorded as a near miss for diagnostics.",
        placeholder="0.25",
        help_text="This affects diagnostics only, not triggering. Keep it below the Detection threshold to capture useful missed-wake-word evidence without logging ordinary silence.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=1.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_CHIME",
        "wakeword_experience",
        "Listening experience",
        "boolean",
        "Listening cue",
        "Plays an acknowledgement sound when a wake word is accepted.",
        help_text="Capture begins immediately; Home Suite does not wait for this cue to finish before recording the command.",
        docs_path="docs/WAKEWORD.md",
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_CHIME_SOUND_FILE",
        "wakeword_experience",
        "Listening experience",
        "choice",
        "Listening cue sound",
        "Audio asset played after wake-word detection.",
        help_text="Choices are discovered from this device's assets directory. A currently configured custom path remains selectable even when it lives elsewhere.",
        docs_path="docs/WAKEWORD.md",
        required=True,
        allow_empty=False,
        dynamic_choices="wakeword_sounds",
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_CHIME_VOLUME",
        "wakeword_experience",
        "Listening experience",
        "number",
        "Listening cue volume",
        "Playback volume for the wake-word acknowledgement sound.",
        placeholder="1.0",
        help_text="Use a value from 0 through 1. This changes cue playback only and does not affect microphone gain.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=1.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_ERROR_TONE_ENABLED",
        "wakeword_experience",
        "Listening experience",
        "boolean",
        "Failure cue",
        "Plays the normal error sound when a wake-word command cannot be processed.",
        help_text="Disable to make incomplete or empty wake-word interactions end silently. Successful commands retain their normal feedback.",
        docs_path="docs/WAKEWORD.md",
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_REARM_SEC",
        "wakeword_experience",
        "Listening experience",
        "number",
        "Minimum rearm delay",
        "Minimum seconds before the listener can accept another wake word after an interaction.",
        placeholder="0.35",
        help_text="Keep this near zero for responsive follow-up commands. A small floor can protect microphones that feed cue audio back into the detector.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=10.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_SUPPRESS_DURING_SFX",
        "wakeword_experience",
        "Listening experience",
        "boolean",
        "Pause detection during sounds",
        "Stops wake-word scoring while Home Suite plays cues and tones.",
        help_text="Disable on devices whose custom model does not react to Home Suite's own sounds. This removes cue-tail dead time but should be tested for false triggers.",
        docs_path="docs/WAKEWORD.md",
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_REARM_SFX_DRAIN_MAX_SEC",
        "wakeword_experience",
        "Listening experience",
        "number",
        "Sound drain wait",
        "Maximum seconds to wait for a completion or error cue before releasing the detector.",
        placeholder="1.0",
        help_text="Set to 0 when detection remains active during sounds. The runtime caps this wait at three seconds.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=3.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_ASYNC_TTS_ENABLED",
        "wakeword_experience",
        "Listening experience",
        "boolean",
        "Background spoken responses",
        "Allows wake-word listening to resume while a local spoken response is still playing.",
        help_text="Enable this to support interruption. It applies only to the wake-word path; PTT response behavior is unchanged.",
        docs_path="docs/WAKEWORD.md",
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_BARGE_IN_ENABLED",
        "wakeword_experience",
        "Listening experience",
        "boolean",
        "Interrupt spoken responses",
        "Lets a new wake word stop local assistant speech and begin another command.",
        help_text="Background spoken responses must also be enabled. Tune the interruption threshold carefully when the speaker and microphone are close together.",
        docs_path="docs/WAKEWORD.md",
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_BARGE_IN_THRESHOLD",
        "wakeword_experience",
        "Listening experience",
        "number",
        "Interruption threshold",
        "Wake-word score required while local assistant speech is playing.",
        placeholder="0.55",
        help_text="This may be lower than the normal Detection threshold to make interruption easier, but lowering it increases the risk of speaker echo causing a trigger.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=1.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_PAUSE_MEDIA_DURING_CAPTURE",
        "wakeword_experience",
        "Listening experience",
        "boolean",
        "Pause room media while listening",
        "Temporarily pauses playing media in the active room before recording the command.",
        help_text="Useful when television or music regularly reaches the microphone. Leave disabled when acoustic echo cancellation already handles room playback.",
        docs_path="docs/WAKEWORD.md",
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STT_MODE",
        "wakeword_transcription",
        "Transcription",
        "choice",
        "Transcription service",
        "Hosted speech-to-text path used for completed wake-word recordings.",
        help_text="Realtime transcription is the recommended path and can consume either live audio or the completed recording. Standard audio transcription keeps the full-file fallback path.",
        docs_path="docs/WAKEWORD.md",
        required=True,
        allow_empty=False,
        choices=(("realtime_stream", "OpenAI Realtime transcription"), ("whisper", "OpenAI audio transcription")),
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_USE_STREAMING_STT",
        "wakeword_transcription",
        "Transcription",
        "boolean",
        "Transcribe while listening",
        "Streams command audio to transcription while local VAD is still recording it.",
        help_text="This can reduce response latency. Disable to record and clean the complete utterance before sending it to the selected transcription service.",
        docs_path="docs/WAKEWORD.md",
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_MAX_SECONDS",
        "wakeword_timing",
        "Advanced command capture",
        "number",
        "Maximum command length",
        "Hard cap in seconds for one wake-word command recording.",
        placeholder="8.0",
        help_text="This is a failsafe for continuous room audio, not an intentional delay. Normal recordings stop earlier when endpointing detects silence.",
        docs_path="docs/WAKEWORD.md",
        minimum=1.0,
        maximum=60.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_FIRST_SPEECH_TIMEOUT_MS",
        "wakeword_timing",
        "Advanced command capture",
        "integer",
        "First-speech timeout",
        "Milliseconds to wait for command speech after a wake-word trigger before ending silently.",
        placeholder="4000",
        help_text="Raise this for users who pause after the wake word. Lower it to release accidental triggers more quickly.",
        docs_path="docs/WAKEWORD.md",
        minimum=250,
        maximum=30000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_PRE_ROLL_MS",
        "wakeword_timing",
        "Advanced command capture",
        "integer",
        "Command pre-roll",
        "Milliseconds of leading command audio retained while voice activity detection locks on.",
        placeholder="800",
        help_text="This buffer starts at detector handoff and does not intentionally include the wake word itself.",
        docs_path="docs/WAKEWORD.md",
        minimum=0,
        maximum=10000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_PRETRIGGER_INCLUDE_MS",
        "wakeword_timing",
        "Advanced command capture",
        "integer",
        "One-breath lookback",
        "Maximum milliseconds of pre-trigger audio appended when command speech begins immediately.",
        placeholder="300",
        help_text="This recovers the first command word in a continuous wake-word-plus-command phrase. It does not drive VAD and should remain short enough to avoid transcribing the wake word.",
        docs_path="docs/WAKEWORD.md",
        minimum=0,
        maximum=5000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_ONE_BREATH_MAX_SPEECH_START_MS",
        "wakeword_timing",
        "Advanced command capture",
        "integer",
        "One-breath speech window",
        "Latest speech-start time that still qualifies for pre-trigger lookback audio.",
        placeholder="450",
        help_text="Shorter values reduce the chance of including the wake word. Longer values are more forgiving when a model triggers slightly before the phrase ends.",
        docs_path="docs/WAKEWORD.md",
        minimum=0,
        maximum=5000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_VAD_ARM_DELAY_MS",
        "wakeword_timing",
        "Advanced command capture",
        "integer",
        "VAD arm delay",
        "Milliseconds of detector-handoff audio buffered before voice activity detection begins scoring.",
        placeholder="250",
        help_text="Recording starts immediately. This delay prevents wake-word tail audio already in the input buffer from becoming the start of the command.",
        docs_path="docs/WAKEWORD.md",
        minimum=0,
        maximum=5000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_CUE_GUARD_MS",
        "wakeword_timing",
        "Advanced command capture",
        "integer",
        "Listening-cue guard",
        "Milliseconds during which strong cue audio may be buffered but cannot start endpointing.",
        placeholder="1000",
        help_text="Use this when the acknowledgement sound leaks into the microphone and looks like speech to command VAD.",
        docs_path="docs/WAKEWORD.md",
        minimum=0,
        maximum=5000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_SILENCE_END_MS",
        "wakeword_timing",
        "Advanced command capture",
        "integer",
        "Silence endpoint",
        "Target milliseconds of silence used to decide that command speech has ended.",
        placeholder="550",
        help_text="Lower values act faster but can cut off natural pauses. Rolling endpoint settings below make this tolerant of occasional false-positive speech frames.",
        docs_path="docs/WAKEWORD.md",
        minimum=100,
        maximum=10000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_MIN_SPEECH_MS",
        "wakeword_timing",
        "Advanced command capture",
        "integer",
        "Minimum speech",
        "Minimum milliseconds of detected speech required to accept a command recording.",
        placeholder="250",
        help_text="Raise this to reject short clicks and cue leakage. Lower it only when legitimate one-word commands are being discarded.",
        docs_path="docs/WAKEWORD.md",
        minimum=50,
        maximum=5000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_ENDPOINT_WINDOW_MS",
        "wakeword_timing",
        "Advanced command capture",
        "integer",
        "Rolling endpoint window",
        "Milliseconds of recent audio considered by noise-tolerant command endpointing.",
        placeholder="700",
        help_text="Set to 0 for strict consecutive-silence endpointing. A rolling window is more tolerant of occasional room-noise frames.",
        docs_path="docs/WAKEWORD.md",
        minimum=0,
        maximum=10000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_ENDPOINT_MIN_SILENCE_RATIO",
        "wakeword_timing",
        "Advanced command capture",
        "number",
        "Required silence ratio",
        "Fraction of the rolling endpoint window that must be silent before capture can stop.",
        placeholder="0.70",
        help_text="Higher values wait for cleaner silence. Lower values stop sooner but may end during noisy pauses.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=1.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_ENDPOINT_TRAILING_SILENCE_MS",
        "wakeword_timing",
        "Advanced command capture",
        "integer",
        "Trailing silence floor",
        "Consecutive silent milliseconds still required at the end of a rolling endpoint window.",
        placeholder="80",
        help_text="This prevents a noisy rolling window from ending on an active speech frame even when its overall silence ratio is high.",
        docs_path="docs/WAKEWORD.md",
        minimum=0,
        maximum=5000,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_STREAM_POST_MEDIA_PAUSE_DRAIN_MS",
        "wakeword_timing",
        "Advanced command capture",
        "integer",
        "Post-media drain",
        "Milliseconds of microphone audio discarded after room media is paused.",
        placeholder="150",
        help_text="Use only with Pause room media while listening. It lets buffered speaker audio clear before command capture is evaluated.",
        docs_path="docs/WAKEWORD.md",
        minimum=0,
        maximum=5000,
        surface="wakeword",
    ),
    _local(
        "PHYSICAL_BUTTONS_ENABLED",
        "buttons",
        "Additional GPIO buttons",
        "boolean",
        "Enable command buttons",
        "Runs auxiliary GPIO buttons that execute configured Home Suite commands.",
        help_text="These buttons do not control microphone capture. Enable them only after assigning each button a unique BCM GPIO pin below.",
        docs_path="docs/GPIO_BUTTONS.md",
        surface="controls",
    ),
    _local(
        "PHYSICAL_BUTTON_ACTIVE_LOW",
        "buttons",
        "Additional GPIO buttons",
        "boolean",
        "Pressed input reads low",
        "Treats a low GPIO level as a pressed command button.",
        help_text="Keep enabled for the common wiring pattern GPIO to button to ground. Disable only when your button hardware drives the pin high when pressed.",
        docs_path="docs/GPIO_BUTTONS.md",
        surface="controls",
    ),
    _local(
        "PHYSICAL_BUTTON_PULL_UP",
        "buttons",
        "Additional GPIO buttons",
        "boolean",
        "Internal pull-up",
        "Enables the Raspberry Pi's internal pull-up resistor on command-button pins.",
        help_text="Keep enabled for buttons wired between GPIO and ground unless your hardware already supplies a stable external pull resistor.",
        docs_path="docs/GPIO_BUTTONS.md",
        surface="controls",
    ),
    _local(
        "PHYSICAL_BUTTON_PINS",
        "buttons",
        "Additional GPIO buttons",
        "json_object",
        "Button-to-pin map",
        "Maps each button number to its BCM GPIO pin.",
        placeholder='{"1": 2, "2": 3}',
        help_text="The guided button mapper links each button ID to an unused BCM GPIO pin. Home Suite stores the result in this dictionary for the runtime.",
        docs_path="docs/GPIO_BUTTONS.md",
        surface="controls",
    ),
    _local(
        "PHYSICAL_BUTTON_ACTIONS",
        "buttons",
        "Additional GPIO buttons",
        "json_object",
        "Button action map",
        "Maps each button and gesture to one or more Home Suite command phrases.",
        placeholder='{"1": {"press": "turn on the office light"}}',
        help_text="The guided button mapper supports single press, double press, and long press. Enter one command per line when a gesture should execute several commands in sequence.",
        docs_path="docs/GPIO_BUTTONS.md",
        surface="controls",
    ),
    _local(
        "ASSISTANT_AUDIO_OUTPUT_MODE",
        "audio",
        "Assistant audio",
        "choice",
        "Response output",
        "Where spoken assistant responses are played.",
        help_text="Local uses this node's ALSA output. Sonos announces through the selected or request-scoped room.",
        docs_path="docs/CONFIGURATION.md",
        required=True,
        allow_empty=False,
        choices=(("local", "Local audio"), ("sonos", "Sonos")),
    ),
    _local(
        "ASSISTANT_AUDIO_OUTPUT_ROOM",
        "audio",
        "Assistant audio",
        "choice",
        "Explicit output room",
        "Optional room used for Sonos responses before the normal fallback chain.",
        help_text="Leave empty to use the request room and then the deployment's default Sonos room.",
        docs_path="docs/CONFIGURATION.md",
        dynamic_choices="rooms_optional",
    ),
    _local(
        "CHATGPT_MODEL",
        "assistant",
        "Conversational assistant",
        "string",
        "Conversational model",
        "OpenAI model used when deterministic routing hands a request to the conversational layer.",
        placeholder="gpt-5.4-mini",
        help_text="Use a model available to the configured OpenAI API project. This does not change deterministic smart-home commands.",
        docs_path="docs/CONFIGURATION.md",
        required=True,
        allow_empty=False,
    ),
    _local(
        "CHATGPT_WEB_SEARCH_ENABLED",
        "assistant",
        "Conversational assistant",
        "boolean",
        "Web search",
        "Allows the conversational fallback to use web search for current information.",
        help_text="Provider usage and charges may apply when a request invokes OpenAI web search.",
        docs_path="docs/INTEGRATIONS.md",
    ),
    _local(
        "UNIFIED_SERVER_ENABLED",
        "network",
        "Companion API",
        "boolean",
        "HTTP and WebSocket API",
        "Exposes the authenticated companion API used by Raycast, menu-bar clients, and satellites.",
        help_text="Disable only when this node should not accept companion-client connections.",
        docs_path="docs/API.md",
    ),
    _local(
        "UNIFIED_SERVER_PORT",
        "network",
        "Companion API",
        "integer",
        "API port",
        "TCP port used by the Home Suite HTTP and WebSocket API.",
        placeholder="8765",
        help_text="Choose an unused port from 1 through 65535. Existing clients must be updated after a change.",
        docs_path="docs/API.md",
        minimum=1,
        maximum=65535,
    ),
    _private(
        "HA_URL",
        "core_services",
        "Core services",
        "url",
        "Home Assistant URL",
        "Base URL Home Suite uses to read state and call Home Assistant services.",
        placeholder="http://homeassistant.local:8123",
        help_text="Use a URL reachable from this node, including the scheme and port when required.",
        docs_path="docs/CREDENTIALS.md",
        required=True,
        allow_empty=False,
        secret=False,
    ),
    _private(
        "HA_TOKEN",
        "core_services",
        "Core services",
        "secret",
        "Home Assistant token",
        "Long-lived access token used to authenticate Home Assistant API requests.",
        help_text="In Home Assistant, open your user profile and create a Long-Lived Access Token. Edit mode keeps the saved token masked until you choose to reveal it.",
        docs_path="docs/CREDENTIALS.md",
        required=True,
        allow_empty=False,
        secret=True,
    ),
    _private(
        "OPENAI_API_KEY",
        "core_services",
        "Core services",
        "secret",
        "OpenAI API key",
        "API key used for configured speech recognition and conversational features.",
        help_text="Create a project API key in the OpenAI platform account described in docs/CREDENTIALS.md. Edit mode keeps the saved key masked until you choose to reveal it.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "HOMESUITE_HTTP_API_KEY",
        "network_credentials",
        "Console and API access",
        "secret",
        "Companion API key",
        "Shared key required by authenticated HTTP and WebSocket companion clients.",
        help_text="Fresh installs generate this automatically. Replacing it requires updating every companion client and restarting the runtime.",
        docs_path="docs/API.md",
        required=True,
        allow_empty=False,
        secret=True,
        restart_services=("homesuite.service", "homesuite-console.service"),
        surface="settings",
    ),
    _private(
        "SATELLITE_BRAIN_API_KEY",
        "satellite",
        "Command processing",
        "secret",
        "Other Home Suite API key",
        "Optional companion API key used only when forwarding commands to another Home Suite instance.",
        help_text="Leave empty when both instances share HOMESUITE_HTTP_API_KEY. Enter the other instance's companion API key when they use different local keys.",
        docs_path="docs/API.md",
        secret=True,
        surface="settings",
    ),
    _private(
        "HOMESUITE_CONSOLE_KEY",
        "network_credentials",
        "Console and API access",
        "secret",
        "Separate console passphrase",
        "Optional passphrase used only for browser-console sign-in.",
        help_text="Leave empty to reuse the companion API key. A separate random value avoids entering the client API credential in a browser.",
        docs_path="docs/CONSOLE.md",
        secret=True,
        restart_services=("homesuite-console.service",),
        surface="settings",
    ),
    _private(
        "PLEX_URL",
        "plex",
        "Plex",
        "url",
        "Plex server URL",
        "Base URL for the Plex Media Server used for library matching and playback.",
        placeholder="http://192.168.1.20:32400",
        help_text="Use the direct URL reachable from this node rather than the Plex web-app URL.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "PLEX_TOKEN",
        "plex",
        "Plex",
        "secret",
        "Plex token",
        "Account token used to search and control the configured Plex server.",
        help_text="Follow the Plex token guidance in docs/CREDENTIALS.md. Edit mode keeps the saved token masked until you choose to reveal it.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "SPOTIFY_CLIENT_ID",
        "spotify",
        "Spotify",
        "string",
        "Client ID",
        "OAuth client identifier for the Spotify developer application.",
        placeholder="Spotify application client ID",
        help_text="Create an application in the Spotify developer dashboard, then run Home Suite's documented authorization flow.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "SPOTIFY_CLIENT_SECRET",
        "spotify",
        "Spotify",
        "secret",
        "Client secret",
        "OAuth client secret paired with the Spotify client ID.",
        help_text="Copy it from the same Spotify developer application. Never place it in tracked configuration.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "SPOTIFY_REFRESH_TOKEN",
        "spotify",
        "Spotify",
        "secret",
        "Refresh token",
        "Long-lived OAuth refresh token authorizing the user's Spotify account.",
        help_text="Generate this by completing the Home Suite Spotify authorization flow; it is not the account password.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "SPOTIFY_DISCOVER_WEEKLY_URI",
        "spotify",
        "Spotify",
        "string",
        "Discover Weekly URI",
        "Optional Spotify playlist URI used for deterministic Discover Weekly playback.",
        placeholder="spotify:playlist:37i9dQZEVXc...",
        help_text="Copy the playlist link in Spotify and use its spotify:playlist URI form. Leave empty when unused.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "TELEGRAM_BOT_TOKEN",
        "telegram",
        "Telegram",
        "secret",
        "Bot token",
        "Token used by the Telegram frontend to poll and reply as your bot.",
        help_text="Create or manage the bot with Telegram's BotFather, then copy the HTTP API token it provides.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
        restart_services=("piphone-telegram.service",),
    ),
    _private(
        "TELEGRAM_ALLOWED_USER_IDS",
        "telegram",
        "Telegram",
        "list_integer",
        "Allowed user IDs",
        "Numeric Telegram user IDs permitted to send commands to the bot.",
        placeholder="123456789",
        help_text="Enter one numeric ID per line. Keep this allowlist narrow even when the bot is in a private chat.",
        docs_path="docs/CREDENTIALS.md",
        restart_services=("piphone-telegram.service",),
    ),
    _private(
        "TELEGRAM_ALLOWED_CHAT_IDS",
        "telegram",
        "Telegram",
        "list_integer",
        "Allowed chat IDs",
        "Optional numeric chat or group IDs permitted to use the bot.",
        placeholder="-1001234567890",
        help_text="Enter one numeric chat ID per line. Negative IDs are normal for Telegram groups and channels.",
        docs_path="docs/CREDENTIALS.md",
        restart_services=("piphone-telegram.service",),
    ),
    _private(
        "PVPORCUPINE_ACCESS_KEY",
        "porcupine",
        "Porcupine wake word",
        "secret",
        "Picovoice access key",
        "Access key required only when WAKEWORD_ENGINE is set to porcupine.",
        help_text="Create a key in the Picovoice Console. Leave empty when using OpenWakeWord.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _local(
        "YOUTUBE_REEL_REFRESH_ENABLED",
        "youtube",
        "YouTube",
        "boolean",
        "Refresh generated playlists",
        "Periodically updates Home Suite's generated YouTube playlists during the configured refresh window.",
        help_text="Enable this on only one always-on Home Suite instance. Keep it disabled on voice satellites to avoid duplicate playlist refresh jobs.",
        docs_path="docs/INTEGRATIONS.md",
        surface="integrations",
    ),
    _private(
        "YOUTUBE_OAUTH_CLIENT_ID",
        "youtube",
        "YouTube",
        "string",
        "OAuth client ID",
        "Client identifier for the Google Cloud OAuth application used by YouTube features.",
        placeholder="Google OAuth desktop client ID",
        help_text="Create the OAuth client described in docs/CREDENTIALS.md, then complete Home Suite's YouTube login flow.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "YOUTUBE_OAUTH_CLIENT_SECRET",
        "youtube",
        "YouTube",
        "secret",
        "OAuth client secret",
        "Secret paired with the YouTube OAuth client ID.",
        help_text="Copy it from the same Google Cloud OAuth client. It is not your Google account password.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "YOUTUBE_OAUTH_REFRESH_TOKEN",
        "youtube",
        "YouTube",
        "secret",
        "OAuth refresh token",
        "Long-lived account authorization produced by Home Suite's YouTube login flow.",
        help_text="Run the documented YouTube login helper after configuring the client ID and secret.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "ALPACA_API_KEY_ID",
        "alpaca",
        "Alpaca market data",
        "string",
        "API key ID",
        "Alpaca key identifier used for read-only stock market data requests.",
        placeholder="Alpaca paper API key ID",
        help_text="Generate Trading API keys in the Alpaca web dashboard. A free Paper Only account is sufficient for the configured IEX feed.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "ALPACA_API_SECRET_KEY",
        "alpaca",
        "Alpaca market data",
        "secret",
        "API secret",
        "Secret paired with the Alpaca market-data key ID.",
        help_text="Copy the secret when Alpaca displays it. Home Suite uses these credentials only for market data, not order submission.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "QBITTORRENT_URL",
        "homelab",
        "Homelab services",
        "url",
        "qBittorrent URL",
        "Base URL for the qBittorrent Web UI API.",
        placeholder="http://192.168.1.30:8080",
        help_text="Use the Web UI address reachable from this node.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "QBITTORRENT_USERNAME",
        "homelab",
        "Homelab services",
        "string",
        "qBittorrent username",
        "Username for the qBittorrent Web UI API.",
        placeholder="admin",
        help_text="Use the username configured under qBittorrent Web UI authentication settings.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "QBITTORRENT_PASSWORD",
        "homelab",
        "Homelab services",
        "secret",
        "qBittorrent password",
        "Password for the qBittorrent Web UI API.",
        help_text="Use a dedicated local credential when possible. Edit mode keeps the saved password masked until you choose to reveal it.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "SEERR_URL",
        "homelab",
        "Homelab services",
        "url",
        "Seerr URL",
        "Base URL for the Seerr or Overseerr API.",
        placeholder="http://192.168.1.30:5055",
        help_text="Use the local Seerr or Overseerr address reachable from this Home Suite node.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "SEERR_API_KEY",
        "homelab",
        "Homelab services",
        "secret",
        "Seerr API key",
        "API key from the Seerr general settings page.",
        help_text="Copy the API key from Seerr settings; do not use the interactive login password.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "RADARR_URL",
        "homelab",
        "Homelab services",
        "url",
        "Radarr URL",
        "Base URL for the Radarr API.",
        placeholder="http://192.168.1.30:7878",
        help_text="Use the local Radarr address reachable from this Home Suite node.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "RADARR_API_KEY",
        "homelab",
        "Homelab services",
        "secret",
        "Radarr API key",
        "API key from Radarr's General settings.",
        help_text="In Radarr, open Settings, General, then copy the API Key from the Security section.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "SONARR_URL",
        "homelab",
        "Homelab services",
        "url",
        "Sonarr URL",
        "Base URL for the Sonarr API.",
        placeholder="http://192.168.1.30:8989",
        help_text="Use the local Sonarr address reachable from this Home Suite node.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "SONARR_API_KEY",
        "homelab",
        "Homelab services",
        "secret",
        "Sonarr API key",
        "API key from Sonarr's General settings.",
        help_text="In Sonarr, open Settings, General, then copy the API Key from the Security section.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "LIDARR_URL",
        "homelab",
        "Homelab services",
        "url",
        "Lidarr URL",
        "Base URL for the Lidarr API.",
        placeholder="http://192.168.1.30:8686",
        help_text="Use the local Lidarr address reachable from this Home Suite node.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "LIDARR_API_KEY",
        "homelab",
        "Homelab services",
        "secret",
        "Lidarr API key",
        "API key from Lidarr's General settings.",
        help_text="In Lidarr, open Settings, General, then copy the API Key from the Security section.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "UPTIME_KUMA_URL",
        "homelab",
        "Homelab services",
        "url",
        "Uptime Kuma URL",
        "Base URL for the Uptime Kuma instance.",
        placeholder="http://192.168.1.30:3001",
        help_text="Use the Uptime Kuma address paired with the public status-page slug below; no admin credential is required.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "UPTIME_KUMA_STATUS_PAGE_SLUG",
        "homelab",
        "Homelab services",
        "string",
        "Status page slug",
        "Public status-page slug used for read-only Uptime Kuma summaries.",
        placeholder="home-services",
        help_text="Use the final path segment from the configured Uptime Kuma status page URL.",
        docs_path="docs/CREDENTIALS.md",
    ),
)


FIELDS_BY_KEY = {field.key: field for field in EDITABLE_FIELDS}


def field_for_key(key: str) -> Optional[ConfigField]:
    return FIELDS_BY_KEY.get(str(key or "").strip())
