"""Schema for console-editable Home Suite configuration values.

The schema is intentionally narrower than app_config.py. It covers values that
can be represented and validated without an arbitrary-code editor. Purpose-built
console editors handle structured room topology, GPIO button mappings, and
device-local microphone profiles.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


LOCAL_PREFS_FILE = "local_prefs.py"
PRIVATE_CONFIG_FILE = "private_config.py"


@dataclass(frozen=True)
class ConfigField:
    key: str
    section: str
    section_label: str
    target_file: str
    value_type: str
    label: str
    description: str
    surface: str = "settings"
    placeholder: str = ""
    help_text: str = ""
    docs_path: str = ""
    required: bool = False
    secret: bool = False
    allow_empty: bool = True
    choices: tuple[tuple[str, str], ...] = ()
    dynamic_choices: Optional[str] = None
    minimum: Optional[float] = None
    maximum: Optional[float] = None
    pattern: Optional[str] = None
    restart_services: tuple[str, ...] = ("homesuite.service",)


def _local(
    key: str,
    section: str,
    section_label: str,
    value_type: str,
    label: str,
    description: str,
    **kwargs,
) -> ConfigField:
    return ConfigField(
        key=key,
        section=section,
        section_label=section_label,
        target_file=LOCAL_PREFS_FILE,
        value_type=value_type,
        label=label,
        description=description,
        **kwargs,
    )


def _private(
    key: str,
    section: str,
    section_label: str,
    value_type: str,
    label: str,
    description: str,
    **kwargs,
) -> ConfigField:
    kwargs.setdefault("surface", "integrations")
    return ConfigField(
        key=key,
        section=section,
        section_label=section_label,
        target_file=PRIVATE_CONFIG_FILE,
        value_type=value_type,
        label=label,
        description=description,
        **kwargs,
    )


EDITABLE_FIELDS = (
    _local(
        "DEFAULT_ROOM",
        "node",
        "Node and role",
        "choice",
        "Default room",
        "Room used when a request does not provide a more specific source room.",
        help_text="The choices come from the shared Rooms registry. Add or duplicate rooms in the Rooms tab, then select the room this node should use by default.",
        docs_path="docs/ROOM_CONFIGURATION.md",
        required=True,
        allow_empty=False,
        dynamic_choices="rooms",
    ),
    _local(
        "PTT_ENABLED",
        "ptt",
        "Push-to-talk (PTT)",
        "boolean",
        "Enable PTT",
        "Uses a maintained GPIO input to open and close microphone listening sessions.",
        help_text="Enable for a held push-to-talk button, telephone hook, foot switch, or another control that remains in one state while Home Suite should listen.",
        docs_path="docs/PTT.md",
        surface="controls",
    ),
    _local(
        "PTT_GPIO_PIN",
        "ptt",
        "Push-to-talk (PTT)",
        "integer",
        "BCM GPIO pin",
        "GPIO input connected to the PTT control, using Raspberry Pi BCM numbering.",
        placeholder="11",
        help_text="BCM numbering is not the physical header-pin number. The default is BCM 11; choose a pin that is not assigned to another configured input.",
        docs_path="docs/PTT.md",
        required=True,
        allow_empty=False,
        minimum=0,
        maximum=27,
        surface="controls",
    ),
    _local(
        "PTT_LISTEN_LEVEL",
        "ptt",
        "Push-to-talk (PTT)",
        "choice",
        "Listen when input is",
        "GPIO level that means the PTT listening session is active.",
        help_text="Choose Low for a control that connects the pin to ground while listening. Choose High only for inverse wiring. Switch mechanics vary, so this is more reliable than assuming pressed or released.",
        docs_path="docs/PTT.md",
        required=True,
        allow_empty=False,
        choices=(("low", "Low (connected to ground)"), ("high", "High (inverse wiring)")),
        surface="controls",
    ),
    _local(
        "PTT_END_BEHAVIOR",
        "ptt",
        "Push-to-talk (PTT)",
        "choice",
        "When the listening state ends",
        "Chooses whether speech already captured is submitted or discarded.",
        help_text="Use Submit for a conventional hold-to-talk button where release finishes the utterance. Use Cancel for a telephone hook where hanging up should discard partial speech and stop the response.",
        docs_path="docs/PTT.md",
        required=True,
        allow_empty=False,
        choices=(("submit", "Submit captured speech"), ("cancel", "Cancel captured speech")),
        surface="controls",
    ),
    _local(
        "START_CHIME_DELAY_SECONDS",
        "ptt",
        "Push-to-talk (PTT)",
        "number",
        "Start cue delay",
        "Seconds to wait after PTT activates before playing its first listening cue.",
        placeholder="0.0",
        help_text="Use 0 for an immediate cue. A telephone handset may need a small delay so the receiver reaches the user's ear first.",
        docs_path="docs/PTT.md",
        minimum=0.0,
        maximum=5.0,
        surface="controls",
    ),
    _local(
        "WAKEWORD_SUPPRESS_WHILE_PTT",
        "ptt",
        "Push-to-talk (PTT)",
        "boolean",
        "Pause wake-word detection during PTT",
        "Prevents the wake-word path from triggering while a PTT session is active.",
        help_text="Keep enabled when one device supports both interaction modes so PTT audio is not interpreted as a second wake-word interaction.",
        docs_path="docs/PTT.md",
        surface="controls",
    ),
    _local(
        "WAKEWORD_ENABLED",
        "wakeword_models",
        "Wake-word models",
        "boolean",
        "Wake-word listening",
        "Runs continuous wake-word detection on this node.",
        help_text="Enable only after the microphone and wake-word model are configured and calibrated.",
        docs_path="docs/WAKEWORD.md",
        surface="managed",
    ),
    _local(
        "COMMAND_PROCESSING_MODE",
        "satellite",
        "Command processing",
        "choice",
        "Process voice commands on",
        "Chooses whether this node executes transcripts itself or sends them to another Home Suite node.",
        help_text="Local is the normal all-in-one mode. Satellite keeps microphone capture, wake-word/PTT, transcription, cues, and spoken responses on this device while the configured brain handles routing, continuity, AI, and actions.",
        docs_path="docs/API.md",
        required=True,
        allow_empty=False,
        choices=(("local", "This device"), ("satellite", "A Home Suite brain")),
    ),
    _local(
        "SATELLITE_BRAIN_URL",
        "satellite",
        "Command processing",
        "url",
        "Brain URL",
        "Authenticated Home Suite companion API that receives this node's transcripts.",
        placeholder="http://homesuite-brain.local:8765",
        help_text="Enter the brain server URL or its full /command URL. The brain must be reachable from this node and use the same API key unless a separate brain key is entered below.",
        docs_path="docs/API.md",
    ),
    _local(
        "WAKEWORD_ENGINE",
        "wakeword",
        "Wake word",
        "choice",
        "Detection engine",
        "Wake-word engine used for continuous local detection.",
        help_text="OpenWakeWord supports local ONNX models. Porcupine requires a Picovoice access key.",
        docs_path="docs/WAKEWORD.md",
        required=True,
        allow_empty=False,
        choices=(("openwakeword", "OpenWakeWord"), ("porcupine", "Porcupine")),
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_MODEL",
        "wakeword_models",
        "Wake-word models",
        "string",
        "Model label",
        "Model name used to select a wake word from the engine's loaded models.",
        placeholder="hal_v2",
        help_text="Use the label reported in WAKEWORD_ENGINE_OPENWAKEWORD_MODELS. It may be blank when model paths provide multiple labels.",
        docs_path="docs/WAKEWORD.md",
        surface="managed",
    ),
    _local(
        "WAKEWORD_MODEL_PATHS",
        "wakeword_models",
        "Wake-word models",
        "list_string",
        "Custom model paths",
        "One local ONNX model path per line for custom OpenWakeWord models.",
        placeholder="/home/jayore/wake_models/hal.onnx",
        help_text="Leave empty to use models bundled with the selected engine. Paths must exist on this node.",
        docs_path="docs/WAKEWORD.md",
        surface="managed",
    ),
    _local(
        "WAKEWORD_THRESHOLD",
        "wakeword",
        "Wake word",
        "number",
        "Detection threshold",
        "Minimum model score required to trigger the wake word.",
        placeholder="0.50",
        help_text="Higher values reduce false triggers but can increase missed wake words. Tune from captured samples rather than guessing.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=1.0,
        surface="wakeword",
    ),
    _local(
        "WAKEWORD_VAD_THRESHOLD",
        "wakeword",
        "Wake word",
        "number",
        "Voice activity threshold",
        "Minimum speech probability required alongside the wake-word score.",
        placeholder="0.50",
        help_text="Set to 0 to disable the VAD gate. Higher values reject more non-speech audio but may reject quiet speech.",
        docs_path="docs/WAKEWORD.md",
        minimum=0.0,
        maximum=1.0,
        surface="wakeword",
    ),
    _local(
        "PHYSICAL_BUTTONS_ENABLED",
        "buttons",
        "Additional GPIO buttons",
        "boolean",
        "Enable command buttons",
        "Runs auxiliary GPIO buttons that execute configured Home Suite commands.",
        help_text="These buttons do not control microphone capture. Enable them only after assigning each button a unique BCM GPIO pin below.",
        docs_path="docs/GPIO_BUTTONS.md",
        surface="controls",
    ),
    _local(
        "PHYSICAL_BUTTON_ACTIVE_LOW",
        "buttons",
        "Additional GPIO buttons",
        "boolean",
        "Pressed input reads low",
        "Treats a low GPIO level as a pressed command button.",
        help_text="Keep enabled for the common wiring pattern GPIO to button to ground. Disable only when your button hardware drives the pin high when pressed.",
        docs_path="docs/GPIO_BUTTONS.md",
        surface="controls",
    ),
    _local(
        "PHYSICAL_BUTTON_PULL_UP",
        "buttons",
        "Additional GPIO buttons",
        "boolean",
        "Internal pull-up",
        "Enables the Raspberry Pi's internal pull-up resistor on command-button pins.",
        help_text="Keep enabled for buttons wired between GPIO and ground unless your hardware already supplies a stable external pull resistor.",
        docs_path="docs/GPIO_BUTTONS.md",
        surface="controls",
    ),
    _local(
        "PHYSICAL_BUTTON_PINS",
        "buttons",
        "Additional GPIO buttons",
        "json_object",
        "Button-to-pin map",
        "Maps each button number to its BCM GPIO pin.",
        placeholder='{"1": 2, "2": 3}',
        help_text="The guided button mapper links each button ID to an unused BCM GPIO pin. Home Suite stores the result in this dictionary for the runtime.",
        docs_path="docs/GPIO_BUTTONS.md",
        surface="controls",
    ),
    _local(
        "PHYSICAL_BUTTON_ACTIONS",
        "buttons",
        "Additional GPIO buttons",
        "json_object",
        "Button action map",
        "Maps each button and gesture to one or more Home Suite command phrases.",
        placeholder='{"1": {"press": "turn on the office light"}}',
        help_text="The guided button mapper supports single press, double press, and long press. Enter one command per line when a gesture should execute several commands in sequence.",
        docs_path="docs/GPIO_BUTTONS.md",
        surface="controls",
    ),
    _local(
        "ASSISTANT_AUDIO_OUTPUT_MODE",
        "audio",
        "Assistant audio",
        "choice",
        "Response output",
        "Where spoken assistant responses are played.",
        help_text="Local uses this node's ALSA output. Sonos announces through the selected or request-scoped room.",
        docs_path="docs/CONFIGURATION.md",
        required=True,
        allow_empty=False,
        choices=(("local", "Local audio"), ("sonos", "Sonos")),
    ),
    _local(
        "ASSISTANT_AUDIO_OUTPUT_ROOM",
        "audio",
        "Assistant audio",
        "choice",
        "Explicit output room",
        "Optional room used for Sonos responses before the normal fallback chain.",
        help_text="Leave empty to use the request room and then the deployment's default Sonos room.",
        docs_path="docs/CONFIGURATION.md",
        dynamic_choices="rooms_optional",
    ),
    _local(
        "CHATGPT_MODEL",
        "assistant",
        "Conversational assistant",
        "string",
        "Conversational model",
        "OpenAI model used when deterministic routing hands a request to the conversational layer.",
        placeholder="gpt-5.4-mini",
        help_text="Use a model available to the configured OpenAI API project. This does not change deterministic smart-home commands.",
        docs_path="docs/CONFIGURATION.md",
        required=True,
        allow_empty=False,
    ),
    _local(
        "CHATGPT_WEB_SEARCH_ENABLED",
        "assistant",
        "Conversational assistant",
        "boolean",
        "Web search",
        "Allows the conversational fallback to use web search for current information.",
        help_text="Provider usage and charges may apply when a request invokes OpenAI web search.",
        docs_path="docs/INTEGRATIONS.md",
    ),
    _local(
        "UNIFIED_SERVER_ENABLED",
        "network",
        "Companion API",
        "boolean",
        "HTTP and WebSocket API",
        "Exposes the authenticated companion API used by Raycast, menu-bar clients, and satellites.",
        help_text="Disable only when this node should not accept companion-client connections.",
        docs_path="docs/API.md",
    ),
    _local(
        "UNIFIED_SERVER_PORT",
        "network",
        "Companion API",
        "integer",
        "API port",
        "TCP port used by the Home Suite HTTP and WebSocket API.",
        placeholder="8765",
        help_text="Choose an unused port from 1 through 65535. Existing clients must be updated after a change.",
        docs_path="docs/API.md",
        minimum=1,
        maximum=65535,
    ),
    _private(
        "HA_URL",
        "core_services",
        "Core services",
        "url",
        "Home Assistant URL",
        "Base URL Home Suite uses to read state and call Home Assistant services.",
        placeholder="http://homeassistant.local:8123",
        help_text="Use a URL reachable from this node, including the scheme and port when required.",
        docs_path="docs/CREDENTIALS.md",
        required=True,
        allow_empty=False,
        secret=False,
    ),
    _private(
        "HA_TOKEN",
        "core_services",
        "Core services",
        "secret",
        "Home Assistant token",
        "Long-lived access token used to authenticate Home Assistant API requests.",
        help_text="In Home Assistant, open your user profile and create a Long-Lived Access Token. Edit mode keeps the saved token masked until you choose to reveal it.",
        docs_path="docs/CREDENTIALS.md",
        required=True,
        allow_empty=False,
        secret=True,
    ),
    _private(
        "OPENAI_API_KEY",
        "core_services",
        "Core services",
        "secret",
        "OpenAI API key",
        "API key used for configured speech recognition and conversational features.",
        help_text="Create a project API key in the OpenAI platform account described in docs/CREDENTIALS.md. Edit mode keeps the saved key masked until you choose to reveal it.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "HOMESUITE_HTTP_API_KEY",
        "network_credentials",
        "Console and API access",
        "secret",
        "Companion API key",
        "Shared key required by authenticated HTTP and WebSocket companion clients.",
        help_text="Fresh installs generate this automatically. Replacing it requires updating every companion client and restarting the runtime.",
        docs_path="docs/API.md",
        required=True,
        allow_empty=False,
        secret=True,
        restart_services=("homesuite.service", "homesuite-console.service"),
        surface="settings",
    ),
    _private(
        "SATELLITE_BRAIN_API_KEY",
        "satellite",
        "Command processing",
        "secret",
        "Brain API key",
        "Optional companion API key used only when forwarding commands to the brain.",
        help_text="Leave empty when this node and the brain share HOMESUITE_HTTP_API_KEY. Enter the brain's companion API key when the two nodes use different local keys.",
        docs_path="docs/API.md",
        secret=True,
        surface="settings",
    ),
    _private(
        "HOMESUITE_CONSOLE_KEY",
        "network_credentials",
        "Console and API access",
        "secret",
        "Separate console passphrase",
        "Optional passphrase used only for browser-console sign-in.",
        help_text="Leave empty to reuse the companion API key. A separate random value avoids entering the client API credential in a browser.",
        docs_path="docs/CONSOLE.md",
        secret=True,
        restart_services=("homesuite-console.service",),
        surface="settings",
    ),
    _private(
        "PLEX_URL",
        "plex",
        "Plex",
        "url",
        "Plex server URL",
        "Base URL for the Plex Media Server used for library matching and playback.",
        placeholder="http://192.168.1.20:32400",
        help_text="Use the direct URL reachable from this node rather than the Plex web-app URL.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "PLEX_TOKEN",
        "plex",
        "Plex",
        "secret",
        "Plex token",
        "Account token used to search and control the configured Plex server.",
        help_text="Follow the Plex token guidance in docs/CREDENTIALS.md. Edit mode keeps the saved token masked until you choose to reveal it.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "SPOTIFY_CLIENT_ID",
        "spotify",
        "Spotify",
        "string",
        "Client ID",
        "OAuth client identifier for the Spotify developer application.",
        placeholder="Spotify application client ID",
        help_text="Create an application in the Spotify developer dashboard, then run Home Suite's documented authorization flow.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "SPOTIFY_CLIENT_SECRET",
        "spotify",
        "Spotify",
        "secret",
        "Client secret",
        "OAuth client secret paired with the Spotify client ID.",
        help_text="Copy it from the same Spotify developer application. Never place it in tracked configuration.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "SPOTIFY_REFRESH_TOKEN",
        "spotify",
        "Spotify",
        "secret",
        "Refresh token",
        "Long-lived OAuth refresh token authorizing the user's Spotify account.",
        help_text="Generate this by completing the Home Suite Spotify authorization flow; it is not the account password.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "SPOTIFY_DISCOVER_WEEKLY_URI",
        "spotify",
        "Spotify",
        "string",
        "Discover Weekly URI",
        "Optional Spotify playlist URI used for deterministic Discover Weekly playback.",
        placeholder="spotify:playlist:37i9dQZEVXc...",
        help_text="Copy the playlist link in Spotify and use its spotify:playlist URI form. Leave empty when unused.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "TELEGRAM_BOT_TOKEN",
        "telegram",
        "Telegram",
        "secret",
        "Bot token",
        "Token used by the Telegram frontend to poll and reply as your bot.",
        help_text="Create or manage the bot with Telegram's BotFather, then copy the HTTP API token it provides.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
        restart_services=("piphone-telegram.service",),
    ),
    _private(
        "TELEGRAM_ALLOWED_USER_IDS",
        "telegram",
        "Telegram",
        "list_integer",
        "Allowed user IDs",
        "Numeric Telegram user IDs permitted to send commands to the bot.",
        placeholder="123456789",
        help_text="Enter one numeric ID per line. Keep this allowlist narrow even when the bot is in a private chat.",
        docs_path="docs/CREDENTIALS.md",
        restart_services=("piphone-telegram.service",),
    ),
    _private(
        "TELEGRAM_ALLOWED_CHAT_IDS",
        "telegram",
        "Telegram",
        "list_integer",
        "Allowed chat IDs",
        "Optional numeric chat or group IDs permitted to use the bot.",
        placeholder="-1001234567890",
        help_text="Enter one numeric chat ID per line. Negative IDs are normal for Telegram groups and channels.",
        docs_path="docs/CREDENTIALS.md",
        restart_services=("piphone-telegram.service",),
    ),
    _private(
        "PVPORCUPINE_ACCESS_KEY",
        "porcupine",
        "Porcupine wake word",
        "secret",
        "Picovoice access key",
        "Access key required only when WAKEWORD_ENGINE is set to porcupine.",
        help_text="Create a key in the Picovoice Console. Leave empty when using OpenWakeWord.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "YOUTUBE_OAUTH_CLIENT_ID",
        "youtube",
        "YouTube",
        "string",
        "OAuth client ID",
        "Client identifier for the Google Cloud OAuth application used by YouTube features.",
        placeholder="Google OAuth desktop client ID",
        help_text="Create the OAuth client described in docs/CREDENTIALS.md, then complete Home Suite's YouTube login flow.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "YOUTUBE_OAUTH_CLIENT_SECRET",
        "youtube",
        "YouTube",
        "secret",
        "OAuth client secret",
        "Secret paired with the YouTube OAuth client ID.",
        help_text="Copy it from the same Google Cloud OAuth client. It is not your Google account password.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "YOUTUBE_OAUTH_REFRESH_TOKEN",
        "youtube",
        "YouTube",
        "secret",
        "OAuth refresh token",
        "Long-lived account authorization produced by Home Suite's YouTube login flow.",
        help_text="Run the documented YouTube login helper after configuring the client ID and secret.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "ALPACA_API_KEY_ID",
        "alpaca",
        "Alpaca market data",
        "string",
        "API key ID",
        "Alpaca key identifier used for read-only stock market data requests.",
        placeholder="Alpaca paper API key ID",
        help_text="Generate Trading API keys in the Alpaca web dashboard. A free Paper Only account is sufficient for the configured IEX feed.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "ALPACA_API_SECRET_KEY",
        "alpaca",
        "Alpaca market data",
        "secret",
        "API secret",
        "Secret paired with the Alpaca market-data key ID.",
        help_text="Copy the secret when Alpaca displays it. Home Suite uses these credentials only for market data, not order submission.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "QBITTORRENT_URL",
        "homelab",
        "Homelab services",
        "url",
        "qBittorrent URL",
        "Base URL for the qBittorrent Web UI API.",
        placeholder="http://192.168.1.30:8080",
        help_text="Use the Web UI address reachable from this node.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "QBITTORRENT_USERNAME",
        "homelab",
        "Homelab services",
        "string",
        "qBittorrent username",
        "Username for the qBittorrent Web UI API.",
        placeholder="admin",
        help_text="Use the username configured under qBittorrent Web UI authentication settings.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "QBITTORRENT_PASSWORD",
        "homelab",
        "Homelab services",
        "secret",
        "qBittorrent password",
        "Password for the qBittorrent Web UI API.",
        help_text="Use a dedicated local credential when possible. Edit mode keeps the saved password masked until you choose to reveal it.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "SEERR_URL",
        "homelab",
        "Homelab services",
        "url",
        "Seerr URL",
        "Base URL for the Seerr or Overseerr API.",
        placeholder="http://192.168.1.30:5055",
        help_text="Use the local Seerr or Overseerr address reachable from this Home Suite node.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "SEERR_API_KEY",
        "homelab",
        "Homelab services",
        "secret",
        "Seerr API key",
        "API key from the Seerr general settings page.",
        help_text="Copy the API key from Seerr settings; do not use the interactive login password.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "RADARR_URL",
        "homelab",
        "Homelab services",
        "url",
        "Radarr URL",
        "Base URL for the Radarr API.",
        placeholder="http://192.168.1.30:7878",
        help_text="Use the local Radarr address reachable from this Home Suite node.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "RADARR_API_KEY",
        "homelab",
        "Homelab services",
        "secret",
        "Radarr API key",
        "API key from Radarr's General settings.",
        help_text="In Radarr, open Settings, General, then copy the API Key from the Security section.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "SONARR_URL",
        "homelab",
        "Homelab services",
        "url",
        "Sonarr URL",
        "Base URL for the Sonarr API.",
        placeholder="http://192.168.1.30:8989",
        help_text="Use the local Sonarr address reachable from this Home Suite node.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "SONARR_API_KEY",
        "homelab",
        "Homelab services",
        "secret",
        "Sonarr API key",
        "API key from Sonarr's General settings.",
        help_text="In Sonarr, open Settings, General, then copy the API Key from the Security section.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "LIDARR_URL",
        "homelab",
        "Homelab services",
        "url",
        "Lidarr URL",
        "Base URL for the Lidarr API.",
        placeholder="http://192.168.1.30:8686",
        help_text="Use the local Lidarr address reachable from this Home Suite node.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "LIDARR_API_KEY",
        "homelab",
        "Homelab services",
        "secret",
        "Lidarr API key",
        "API key from Lidarr's General settings.",
        help_text="In Lidarr, open Settings, General, then copy the API Key from the Security section.",
        docs_path="docs/CREDENTIALS.md",
        secret=True,
    ),
    _private(
        "UPTIME_KUMA_URL",
        "homelab",
        "Homelab services",
        "url",
        "Uptime Kuma URL",
        "Base URL for the Uptime Kuma instance.",
        placeholder="http://192.168.1.30:3001",
        help_text="Use the Uptime Kuma address paired with the public status-page slug below; no admin credential is required.",
        docs_path="docs/CREDENTIALS.md",
    ),
    _private(
        "UPTIME_KUMA_STATUS_PAGE_SLUG",
        "homelab",
        "Homelab services",
        "string",
        "Status page slug",
        "Public status-page slug used for read-only Uptime Kuma summaries.",
        placeholder="home-services",
        help_text="Use the final path segment from the configured Uptime Kuma status page URL.",
        docs_path="docs/CREDENTIALS.md",
    ),
)


FIELDS_BY_KEY = {field.key: field for field in EDITABLE_FIELDS}


def field_for_key(key: str) -> Optional[ConfigField]:
    return FIELDS_BY_KEY.get(str(key or "").strip())
